<?php 
/**
	Admin Page Framework v3.8.20 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/php-shark>
	Copyright (c) 2013-2019, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class PHPShark_AdminPageFramework_Form_View___CSS_term_meta extends PHPShark_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".php-shark-form-table-outer-row-term_meta,.php-shark-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.php-shark-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.php-shark-form-table-term_meta .php-shark-sectionset,.php-shark-form-table-term_meta .php-shark-section {margin-bottom: 0;}.php-shark-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.php-shark-form-table-term_meta.add-new-term .php-shark-section .form-table > tbody > tr > td,.php-shark-form-table-term_meta.add-new-term .php-shark-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.php-shark-form-table-term_meta.add-new-term .php-shark-field {width: auto;}.php-shark-form-table-term_meta.add-new-term .php-shark-field {max-width: 100%;}.php-shark-form-table-term_meta.add-new-term .sortable .php-shark-field {width: auto;} .php-shark-form-table-term_meta.add-new-term .php-shark-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.php-shark-form-table-term_meta .php-shark-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.php-shark-form-table-term_meta .php-shark-collapsible-title h3 {margin: 0;}.php-shark-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.php-shark-form-table-term_meta .php-shark-section-tab h4 {margin: 0;} ";
    }
    }
    